spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PHARMACY_SYSTEM;encrypt=false;;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123456

server.port=8080

spring.main.allow-bean-definition-overriding=true
spring.data.jdbc.repositories.enabled=false

#Send mail
spring.mail.host=smtp.gmail.com 
spring.mail.port=587 
spring.mail.username=vanbac1288@gmail.com
spring.mail.password=phaidauCUOCTINH0507
spring.mail.properties.mail.smtp.auth=true 
spring.mail.properties.mail.smtp.starttls.enable=true